name: at_lookup
description: Library for executing at commands on a secondary server. Example - scan. update, lookup, llookup, plookup etc.
version: 2.0.1
repository: https://github.com/atsign-foundation/at_libraries
homepage: https://atsign.dev

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.8.0
  crypton: ^2.0.1
  crypto: ^3.0.1
  at_utils: ^2.0.1
  at_commons: ^2.0.1


dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.1
