name: at_lookup
description: Library for executing at commands on a secondary server. Example - scan. update, lookup, llookup, plookup etc.
version: 1.0.0+5
repository: https://github.com/atsign-foundation/at_libraries
homepage: https://atsign.dev

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  path: ^1.6.0
  crypton: ^1.1.0
  crypto: ^2.1.5
  at_utils: ^1.0.1+5
  at_commons: ^1.0.1+5

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
