name: at_lookup_example
description: An example application to demostrate the at_lookup package usage.
version: 1.0.0

environment:
  sdk: '>=2.14.4 <4.0.0'


dependencies:
  at_utils: ^3.0.2
  at_commons: ^3.0.2
  at_lookup: ^3.0.5

dependency_overrides:
  at_lookup:
    git:
      url: https://github.com/atsign-foundation/at_libraries.git
      path: packages/at_lookup
      ref: dart-3
  at_commons:
    git:
      url: https://github.com/atsign-foundation/at_tools.git
      path: packages/at_commons
      ref: dart-3
  at_utils:
    git:
      url: https://github.com/atsign-foundation/at_tools.git
      path: packages/at_commons
      ref: dart-3

dev_dependencies:
  lints: ^1.0.0
