name: at_onboarding_cli
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.15.1 <3.0.0'


dependencies:
   at_utils: ^3.0.4
   at_client: ^3.0.13
   at_lookup: ^3.0.7
   zxing2: ^0.1.0
   image: ^3.1.1
   crypton: ^2.0.3
   at_commons: ^3.0.8
   encrypt: ^5.0.1
   at_server_status: 1.0.3
   ##at_persistence_secondary_server: ^3.0.19

dependency_overrides:
  at_client:
        git:
          url: https://github.com/atsign-foundation/at_client_sdk.git
          path: at_client
          ref: trunk


dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  at_demo_data: ^0.0.3+1
