name: at_server_status
description: The at_server_status library provides an easy means to check on the status of the @root server as well as the @server for a particular @sign.
documentation: https://atsign.dev/apidocs
repository: https://github.com/atsign-foundation/at_libraries
homepage: https://atsign.dev
version: 0.1.0+2

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  at_lookup:
    git:
      url: https://github.com/atsign-foundation/at_libraries.git
      path: at_lookup
      ref: null_safety
      version: ^1.0.0+5
  uuid: ^3.0.4

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.1
