name: at_server_status
description: A Dart library that provides a means to check on the status of the @‎root server as well as the secondary server for any particular @‎sign. 
documentation: https://atsign.dev/apidocs
repository: https://github.com/atsign-foundation/at_libraries
homepage: https://atsign.dev
version: 1.0.1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  at_lookup: ^2.0.3
  at_utils: ^2.0.3
  at_commons: ^2.0.3
  uuid: ^3.0.4

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.1
