name: at_server_status
description: The at_server_status library provides an easy means to check on the status of the @root server as well as the @server for a particular @sign.
documentation: https://atsign.dev/apidocs
repository: https://github.com/atsign-foundation/at_libraries
homepage: https://atsign.dev
publish_to: none
version: 0.2.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  at_lookup: ^2.0.0
  at_utils: ^2.0.0
  at_commons: ^2.0.0
  uuid: ^3.0.4

#dependency_overrides:
#  at_lookup:
#    path: ../at_lookup

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.1
