name: functional_tests
description: functional tests for at_onboarding_cli.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.14.4 <3.0.0'


dependencies:
  at_onboarding_cli:
    path: ../

dependency_overrides:
  at_lookup:
    path: ../../at_lookup
  at_client:
    git:
      url: https://github.com/atsign-foundation/at_client_sdk.git
      path: at_client
      ref: trunk


dev_dependencies:
  lints: ^1.0.0
  test: ^1.17.2
  at_demo_data: ^1.0.0
