name: at_contact
description: A starting point for Dart libraries or applications.
version: 1.1.0
repository: https://github.com/atsign-foundation/at_libraries
homepage: https://atsign.dev
publish_to: none

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  intl: ^0.16.1
  at_client: ^1.0.1+10

dependency_overrides:
  at_client:
    git:
      url: https://github.com/atsign-foundation/at_client_sdk.git
      path: at_client
      ref: null_safety
      version: ^1.1.0
  at_persistence_spec:
    git:
      url: https://github.com/atsign-foundation/at_server.git
      path: at_persistence/at_persistence_spec
      ref: null_safety
      version: ^1.1.0
  at_persistence_secondary_server:
    git:
      url: https://github.com/atsign-foundation/at_server.git
      path: at_secondary/at_persistence_secondary_server
      ref: null_safety
      version: ^1.1.0
  at_lookup:
    git:
      url: https://github.com/atsign-foundation/at_libraries.git
      path: at_lookup
      ref: null_safety
      version: ^1.1.0
  at_utils:
    git:
      url: https://github.com/atsign-foundation/at_tools.git
      path: at_utils
      ref: null_safety
      version: ^1.1.0
  at_commons:
    git:
      url: https://github.com/atsign-foundation/at_tools.git
      path: at_commons
      ref: null_safety
      version: ^1.1.0
  uuid: ^3.0.4

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.15.4
