name: at_contact
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://atsign.dev

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  intl: ^0.16.1
  at_client:
    git:
      url: git@github.com:atsign-foundation/at_client_sdk.git
      path: at_client
      ref: master

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
