name: at_contact
description: A starting point for Dart libraries or applications.
version: 2.0.0
repository: https://github.com/atsign-foundation/at_libraries
homepage: https://atsign.dev

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  intl: ^0.17.1
  at_client: ^2.0.0
  at_commons: ^2.0.0
  at_utils: ^2.0.0
  uuid: ^3.0.4

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.15.4
